import 'dart:convert';

import 'package:dio/dio.dart';

import '../../../core/config/env.dart';
import '../../../core/network/api_error.dart';
import '../../../core/network/json.dart';
import '../../../core/network/session_store.dart';

/// A TOTP factor as GoTrue holds it.
///
/// `verified` is the only status that means two-factor authentication is on.
/// `unverified` is a setup that was started and never confirmed with a code:
/// it protects nothing, and signing in never asks for it.
class TotpFactor {
  const TotpFactor({
    required this.id,
    required this.status,
    this.friendlyName,
    this.createdAt,
  });

  final String id;
  final String status;
  final String? friendlyName;
  final DateTime? createdAt;

  bool get isVerified => status == 'verified';

  static TotpFactor? fromJson(Map<String, dynamic> json) {
    final id = asString(json['id']);
    final type = asString(json['factor_type']) ?? asString(json['type']);
    if (id == null || (type != null && type != 'totp')) return null;
    return TotpFactor(
      id: id,
      status: asString(json['status']) ?? 'unverified',
      friendlyName: asString(json['friendly_name']),
      createdAt: asDate(json['created_at']),
    );
  }

  /// The TOTP factors on a GoTrue user object. Phone factors, if the server
  /// ever enables them, are not this feature's and are left out.
  static List<TotpFactor> listFrom(Map<String, dynamic>? user) {
    final raw = user?['factors'];
    if (raw is! List) return const [];
    return [
      for (final item in raw)
        if (item is Map) ?TotpFactor.fromJson(item.cast<String, dynamic>()),
    ];
  }
}

/// What GoTrue hands back when a factor is enrolled.
///
/// [secret] and [qrSvg] are the shared key itself. They exist for the length
/// of the setup screen and nowhere else: never logged, never written to disk,
/// never put in the session. Once the factor is verified the authenticator app
/// holds the only copy the client ever needs.
class TotpEnrollment {
  const TotpEnrollment({
    required this.factorId,
    required this.secret,
    required this.qrSvg,
    required this.uri,
  });

  final String factorId;
  final String secret;

  /// The SVG markup of the QR code, decoded from GoTrue's data URI.
  final String qrSvg;

  /// The `otpauth://` URI the QR code encodes.
  final String uri;
}

/// GoTrue's own multi-factor API. No second 2FA system is built here: every
/// secret is generated by the server, every code is checked by the server, and
/// the session is only raised to `aal2` by the server.
///
///   * `POST /factors` -- enroll a TOTP factor (answers the secret and QR).
///   * `POST /factors/{id}/challenge` -- start a verification.
///   * `POST /factors/{id}/verify` -- check a code; answers an `aal2` session.
///   * `DELETE /factors/{id}` -- remove a factor. GoTrue requires `aal2`.
///
/// Every call carries the token it is given rather than reading the stored
/// session: during sign-in the token being upgraded is deliberately *not*
/// stored yet, and must not be.
class MfaRepository {
  MfaRepository({Dio? dio})
    : // Its own Dio with no interceptors, for the reason AuthRepository gives:
      // the shared client refreshes tokens against this same server, and a
      // failed verification must never set off a refresh.
      _dio =
          dio ??
          Dio(
            BaseOptions(
              baseUrl: Env.authBaseUrl,
              connectTimeout: Env.requestTimeout,
              receiveTimeout: Env.requestTimeout,
              contentType: 'application/json',
            ),
          );

  static final MfaRepository instance = MfaRepository();

  final Dio _dio;

  Options _bearer(String token) =>
      Options(headers: {'Authorization': 'Bearer $token'});

  /// The user's TOTP factors, read fresh from the server.
  Future<List<TotpFactor>> factors(String accessToken) async {
    try {
      final res = await _dio.get('/user', options: _bearer(accessToken));
      return TotpFactor.listFrom(asMap(res.data));
    } on DioException catch (e) {
      throw _error(e);
    }
  }

  /// Starts a TOTP setup. The factor stays `unverified` -- and 2FA stays off --
  /// until [verify] succeeds with a code from the authenticator app.
  ///
  /// Any earlier setup that was never finished is removed first. GoTrue refuses
  /// a second factor with the same name, and an abandoned half-setup is not
  /// something to keep.
  Future<TotpEnrollment> enroll(String accessToken) async {
    for (final stale in await factors(accessToken)) {
      if (!stale.isVerified) await unenroll(accessToken, stale.id);
    }
    try {
      final res = await _dio.post(
        '/factors',
        data: {
          'factor_type': 'totp',
          'friendly_name': 'Gtradea authenticator',
          'issuer': 'Gtradea',
        },
        options: _bearer(accessToken),
      );
      final body = asMap(res.data);
      final totp = asMap(body['totp']);
      final id = asString(body['id']);
      final secret = asString(totp['secret']);
      final qr = asString(totp['qr_code']);
      if (id == null || secret == null || qr == null) {
        throw const ApiError(
          statusCode: null,
          message: 'The server did not return the setup key. Try again.',
          local: true,
        );
      }
      return TotpEnrollment(
        factorId: id,
        secret: secret,
        qrSvg: svgFromDataUri(qr),
        uri: asString(totp['uri']) ?? '',
      );
    } on DioException catch (e) {
      throw _error(e);
    }
  }

  /// Opens a verification for [factorId]. Returns the challenge id [verify]
  /// needs. Challenges expire; [verify] reports that and the caller asks again.
  Future<String> challenge(String accessToken, String factorId) async {
    try {
      final res = await _dio.post(
        '/factors/$factorId/challenge',
        data: const <String, dynamic>{},
        options: _bearer(accessToken),
      );
      final id = asString(asMap(res.data)['id']);
      if (id == null) {
        throw const ApiError(
          statusCode: null,
          message: 'The server did not start verification. Try again.',
          local: true,
        );
      }
      return id;
    } on DioException catch (e) {
      throw _error(e);
    }
  }

  /// Checks [code] on the server. On success GoTrue answers a new session at
  /// `aal2`; it is returned, not stored -- the caller decides where it goes.
  ///
  /// A wrong code throws with [MfaError.invalidCode]; an expired challenge with
  /// [MfaError.challengeExpired]. Nothing about the code is judged here.
  Future<AuthSession> verify({
    required String accessToken,
    required String factorId,
    required String challengeId,
    required String code,
  }) async {
    try {
      final res = await _dio.post(
        '/factors/$factorId/verify',
        data: {'challenge_id': challengeId, 'code': code.trim()},
        options: _bearer(accessToken),
      );
      return AuthSession.fromJson(asMap(res.data));
    } on DioException catch (e) {
      throw _error(e);
    } on FormatException {
      throw const ApiError(
        statusCode: null,
        message: 'The server did not return a session. Try again.',
        local: true,
      );
    }
  }

  /// Removes a factor. For a verified factor GoTrue requires an `aal2` token,
  /// which is what stops a stolen password from switching 2FA off.
  Future<void> unenroll(String accessToken, String factorId) async {
    try {
      await _dio.delete('/factors/$factorId', options: _bearer(accessToken));
    } on DioException catch (e) {
      throw _error(e);
    }
  }

  /// The assurance level a token was issued at: `aal1` (password or provider
  /// only) or `aal2` (a second factor was verified).
  ///
  /// Read from the JWT payload **only to choose which screen to show**. The
  /// server is what enforces it -- a token edited to claim `aal2` fails the
  /// signature check on every request -- so nothing here trusts this value for
  /// access.
  static String aalOf(String accessToken) {
    final parts = accessToken.split('.');
    if (parts.length != 3) return 'aal1';
    try {
      final payload = utf8.decode(
        base64Url.decode(base64Url.normalize(parts[1])),
      );
      return asString(asMap(jsonDecode(payload))['aal']) ?? 'aal1';
    } catch (_) {
      return 'aal1';
    }
  }

  /// True when this session belongs to an account with 2FA on but has not
  /// passed it yet -- the one state that must never be treated as signed in.
  static bool needsSecondFactor(AuthSession session) =>
      TotpFactor.listFrom(session.user).any((f) => f.isVerified) &&
      aalOf(session.accessToken) != 'aal2';

  /// GoTrue sends the QR code as `data:image/svg+xml;utf-8,<svg ...>`, plain or
  /// percent-encoded, or base64. Whichever it is, the SVG markup comes back.
  static String svgFromDataUri(String dataUri) {
    final comma = dataUri.indexOf(',');
    if (!dataUri.startsWith('data:') || comma < 0) return dataUri;
    final header = dataUri.substring(0, comma);
    final data = dataUri.substring(comma + 1);
    if (header.contains(';base64')) {
      return utf8.decode(base64.decode(data));
    }
    return data.contains('%3C') || data.contains('%3c')
        ? Uri.decodeComponent(data)
        : data;
  }

  static ApiError _error(DioException e) {
    final base = ApiError.fromDio(e);
    final code = asString(asMap(base.body)['error_code']);
    final message = switch (code) {
      'mfa_verification_failed' => MfaError.invalidCode,
      'mfa_challenge_expired' => MfaError.challengeExpired,
      'mfa_verification_rejected' => MfaError.invalidCode,
      'insufficient_aal' =>
        'Confirm with your authenticator code before changing this.',
      'too_many_enrolled_mfa_factors' =>
        'Too many authenticator setups on this account. Remove one first.',
      'over_request_rate_limit' || 'over_email_send_rate_limit' =>
        'Too many attempts. Wait a minute and try again.',
      _ when base.statusCode == 429 =>
        'Too many attempts. Wait a minute and try again.',
      _ => base.message,
    };
    return ApiError(
      statusCode: base.statusCode,
      message: message,
      body: base.body,
    );
  }
}

/// The messages callers compare against to decide what to do next, kept in
/// one place so the screen and the repository cannot disagree on the words.
abstract final class MfaError {
  static const invalidCode = 'That code is not correct. Check your app and try again.';
  static const challengeExpired = 'That code has expired. Enter the current one.';

  static bool isInvalidCode(ApiError e) => e.message == invalidCode;
  static bool isExpired(ApiError e) => e.message == challengeExpired;
}
